name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.py

    - name: Run basic unit tests
      run: |
        echo "Pytest"

  sast-bandit:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
    - uses: actions/checkout@v3

    - name: Install Bandit
      run: |
        pip install bandit

    - name: Run Bandit SAST
      run: |
        bandit -r . -ll || exit 1

  deploy-to-staging:
    runs-on: ubuntu-latest
    needs: sast-bandit
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Deploy placeholder
      run: echo "Deployment location"
