name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest # Added to ensure pytest is installed

      - name: Run tests
        run: |
          pytest

      - name: Run Bandit Security Scan
        run: |
          pip install bandit
          bandit -r . -lll --exit-zero

  dast:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run app in background
        run: |
          nohup python app.py &
          sleep 10

      - name: Run OWASP ZAP Baseline Scan (Generate Reports Only)
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://localhost:5000'
          # Remove artifact_name here as we will handle upload manually
          # The action will still generate report files (e.g., report_json.json, report_md.md, report_html.html)
          # in the workspace as seen in your logs.

      - name: Upload ZAP Scan Reports
        uses: actions/upload-artifact@v3 # Use native GitHub action for uploading artifacts
        with:
          name: zap-scan-reports
          path: |
            report_json.json
            report_md.md
            report_html.html
