name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest # Added to ensure pytest is installed

      - name: Run tests
        run: |
          pytest

      - name: Run Bandit Security Scan
        run: |
          pip install bandit
          bandit -r . -lll --exit-zero

  dast:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run app in background
        run: |
          nohup python app.py &
          sleep 10

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://localhost:5000'
          cmd_options: '-J zap_report.json -w zap_report.md -r zap_report.html' # Updated report filenames
          allow_issue_writing: false # Prevent automatic GitHub issue creation

      - name: Upload ZAP reports manually # Changed name from 'Upload ZAP Scan Artifacts' to 'Upload ZAP reports manually'
        uses: actions/upload-artifact@v4
        with:
          name: zap-reports # Updated artifact name
          path: | # Paths to the generated report files (updated filenames)
            zap_report.json
            zap_report.md
            zap_report.html
